webtalk_init -webtalk_dir /home/spdy18695/workbench/CODES/Vivado_projects/Systolic_Array/Systolic_Array.sim/sim_1/behav/xsim/xsim.dir/carryskipadd_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan  6 22:04:18 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "84d9afd0-2a2f-4b3b-a02c-9fa51ec9aa6c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "888e7af2256e47da8ca96fb35cbd6188" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3642.209 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "60 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125892_KB" -context "xsim\\usage"
webtalk_transmit -clientid 380739062 -regid "" -xml /home/spdy18695/workbench/CODES/Vivado_projects/Systolic_Array/Systolic_Array.sim/sim_1/behav/xsim/xsim.dir/carryskipadd_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/spdy18695/workbench/CODES/Vivado_projects/Systolic_Array/Systolic_Array.sim/sim_1/behav/xsim/xsim.dir/carryskipadd_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/spdy18695/workbench/CODES/Vivado_projects/Systolic_Array/Systolic_Array.sim/sim_1/behav/xsim/xsim.dir/carryskipadd_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
