#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Apr 13 15:10:46 IST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 888e7af2256e47da8ca96fb35cbd6188 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot Systolic_Processor_tb_behav xil_defaultlib.Systolic_Processor_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 888e7af2256e47da8ca96fb35cbd6188 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot Systolic_Processor_tb_behav xil_defaultlib.Systolic_Processor_tb xil_defaultlib.glbl -log elaborate.log

