#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Apr 13 14:32:14 IST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Systolic_Processor_tb_behav -key {Behavioral:sim_1:Functional:Systolic_Processor_tb} -tclbatch Systolic_Processor_tb.tcl -view /home/spdy18695/workbench/CODES/Vivado_projects/Systolic_Array/Systolic_Array.srcs/sim_1/imports/Systolic_Array/Systolic_Array.srcs/top_BOOTH_tb_behav1.wcfg -view /home/spdy18695/workbench/CODES/Vivado_projects/Systolic_Array/Systolic_Array.srcs/sim_1/imports/Systolic_Array/roundunit_tb_behav.wcfg -view /home/spdy18695/workbench/CODES/Vivado_projects/Systolic_Array/Systolic_Array.srcs/sim_1/imports/Systolic_Array/Systolic_Processor_tb.wcfg -log simulate.log"
xsim Systolic_Processor_tb_behav -key {Behavioral:sim_1:Functional:Systolic_Processor_tb} -tclbatch Systolic_Processor_tb.tcl -view /home/spdy18695/workbench/CODES/Vivado_projects/Systolic_Array/Systolic_Array.srcs/sim_1/imports/Systolic_Array/Systolic_Array.srcs/top_BOOTH_tb_behav1.wcfg -view /home/spdy18695/workbench/CODES/Vivado_projects/Systolic_Array/Systolic_Array.srcs/sim_1/imports/Systolic_Array/roundunit_tb_behav.wcfg -view /home/spdy18695/workbench/CODES/Vivado_projects/Systolic_Array/Systolic_Array.srcs/sim_1/imports/Systolic_Array/Systolic_Processor_tb.wcfg -log simulate.log

